paths:
  /mangas:
    get:
      tags:
        - User Mangas # Oddiy foydalanuvchilar uchun
      summary: Barcha mangalarni olish
      responses:
        200:
          description: OK

    post:
      tags:
        - Admin Mangas # Adminlar uchun
      summary: Yangi manga yaratish (Faqat Admin)
      responses:
        201:
          description: Created

  /mangas/{id}:
    get:
      tags:
        - User Mangas
      summary: ID bo‘yicha manga olish
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
